Add units tests for Message
colab-chat/colab-server pull request #30
Opened 2017-08-06 12:56 UTC by matthew-d-jones

These are the first unit tests, so I've added how to run them to the readme. It also required tweaking the app `__init__` to avoid trying to connect to Kafka unless the app is actually being created.

2017-08-06 16:58 UTC, AntonPiccardoSelg requested changes

2017-08-06 16:58 UTC, AntonPiccardoSelg commented on colab.py
> +                    default=0)
Good change. Is 0, 1, 2 stil necessary?

2017-08-06 16:58 UTC, AntonPiccardoSelg commented on tests/env.py
> +    os.path.dirname(
`os.path.direname` should only be required once, no?

2017-08-07 09:15 UTC, matthew-d-jones commented on tests/env.py
> +    os.path.dirname(
(I also made this change, it hasn't got updated because I removed the following line)

2017-08-23 20:30 UTC, AntonPiccardoSelg approved these changes

2017-08-23 20:30 UTC, merged